### ISSUE TITLE
Status code must be an integer value between 1xx and 5xx

### ISSUE THREAD

**Issue by ClaudiuTodosia** [spatie/crawler#271] opened 2019-11-18 09:51 UTC
Hello,
I receive this answer when I'm using the crawler like this:
![image](https://user-images.githubusercontent.com/46482024/69042170-6ee17f00-09f9-11ea-9baf-4d890be9e357.png)
![image](https://user-images.githubusercontent.com/46482024/69042202-7c970480-09f9-11ea-81c1-9b97222e9bcd.png)

**Comment by Redominus** [comment] 2019-11-18 10:17
It looks like there is some code somwhere that is trying to create a PSR-7 response with status code different from that values. Probably a status code 0 retuned by curl when there are connection problems(DNS, Proxy, SSL, IP, etc). If you are using guzzlehttp as the psr-7 implementation there should be no problems. Some implementations of PSR-7 ResponseInterface only allow values between  those numbers([Symfony](https://github.com/symfony/http-foundation/blob/68efb46314ab9944cb5af220a26fec9c02b4e20a/Response.php#L1082)).

**Comment by ClaudiuTodosia** [comment] 2019-11-18 10:21
Ok, any idea how can I fix this problem? because if I lower the maximum crawler count it will work but I need all the pages to be crawled... And if I remove the set maximum crawler the I will have the same error.

**Comment by Redominus** [comment] 2019-11-18 10:45
Guzzle has recently added a [check](https://github.com/guzzle/psr7/commit/c5aea30ff82a3565e6d3decd18d74257c033daf6#diff-f89246dce7e387482b2c6c584a5e7e9dR128) to enforce those numbers. :disappointed: 
I would suggest an x-debug session with automatic breakpoin on _InvalidArgumentException_ exception.

**Comment by bengower** [comment] 2020-01-03 17:47
I reckon it could be related to this (bot blocking):
https://stackoverflow.com/questions/46214017/public-linkedin-profile-url-returns-server-status-code-999/49856601

Below will throw an error on code 999 as it's out of the range specified so it's not an entirely accurate error message. Should really throw an error for blocked bots or code 999

guzzlehttp/psr7/src/Response.php
private function assertStatusCodeRange($statusCode)
    {   
        if ($statusCode < 100 || $statusCode >= 600) {
            throw new \InvalidArgumentException('Status code must be an integer value between 1xx and 5xx.');
        }
    }

**Comment by Skullbock** [comment] 2020-01-24 17:23
Same here.
Basically, if any site responds with a different status code than guzzle expects (in my case, 999), the response class of guzzle triggers an InvalidArgumentException.

The issue is that since all the crawling is done in a queue, and this exception is not intercepted by the Guzzlehttp Pool class (it only intercepts the RequestException), it bubbles up and can't be intercepted through the crawlFailed() method in this package.

Unfortunately i think this is not solvable if not by Guzzle itself (catching any exception and bubbling it up with another callback i think).

@freekmurze any thoughts on this?

**Comment by freekmurze** [comment] 2020-01-25 09:34
I'm thinking this should be changed at Guzzle's end indeed.

**Comment by Skullbock** [comment] 2020-01-28 08:51
Brought this up to the guzzle team with a possible solution here: https://github.com/guzzle/guzzle/issues/2534

**Comment by williamjulianvicary** [comment] 2020-02-10 23:37
Just to jump in as I've been debugging this this evening (my comments here: https://github.com/guzzle/guzzle/issues/2534) this is a core bug in my opinion which was caused by the PSR7 update to the HTTP Response object (which validates the status codes).

Essentially these exceptions are getting caught up within the Curl Multi header callback which generates the response, these exceptions should be caught and treated as an error during header collection - currently they aren't and instead the exception is causing no end of trouble. (It goes beyond just occasionally stalling execution - in my tests it's actually blocking requests that would otherwise complete, marking them as failed when they are not - presumably because curl handles aren't being regenerated or similar).

There is no simple (read: not a bodge) solution to this problem as far as I can tell, Curl relies on an appropriate response (-1 on error, not an exception) to handle the execution flow. These exceptions are breaking something within the core, and Curl Multi has always been a little rogue within PHP too - couple that with some nice race conditions on the promise state and you've got a headache! 

A roll-back of PSR7 changes to the Response object and a try/catch to pick up any other exceptions (see my notes in the other thread) would solve this, or alternatively avoiding PSR7 Response altogether (unlikely) or catching the assertion exceptions/pre-validating the status code and handling these gracefully are all doable, but it depends what Guzzle wants in the core. 

Anyway, no immediate solution unfortunately, this is blocking some internal tech though so I'm on-board on finding a fix for this.

**Comment by Skullbock** [comment] 2020-02-11 07:56
Hey @williamjulianvicary thanks for taking the time to answer here too.
I'll be following both issues so if i can help in any way, i'll be notified.
Thanks again!

**Comment by runningnet** [comment] 2020-02-21 11:07
For me a ` composer require guzzlehttp/guzzle:~6.0` fixed the problem in my Project

**Comment by williamjulianvicary** [comment] 2020-02-21 13:32
This is an intermittent problem that you’ll hit on the 6.5.2 branch (latest branch for v6). I’ve submitted a pull request in the link I submitted above that solves this issue - I’m maintaining a fork if you want to alias to that meanwhile!

**Comment by bobemoe** [comment] 2020-02-23 08:33
thanks @williamjulianvicary, just confirming your patch appears to have fixed this issue for me :)

**Closed** 2020-02-23 13:17 UTC

**Comment by lilessam** [comment] 2020-06-11 13:24
Just in case someone still looks for detailed solution:

```
composer require cweagans/composer-patches
```

then add in `extras` in your `composer.json` the following:
```
"patches": {
    "guzzlehttp/guzzle": {
        "Status code must be an integer value between 1xx and 5xx": "https://patch-diff.githubusercontent.com/raw/guzzle/guzzle/pull/2591.patch"
    }
}
```

then run `composer install` again and should be good.

**Comment by strarsis** [comment] 2020-09-19 07:48
Thanks for the patch!
This is indeed a sore point in Guzzle as there is no way getting around untypical HTTP status codes with the current Guzzle code.

**Comment by strarsis** [comment] 2020-09-19 21:35
@lilessam: I added the patch to a generated OpenAPI PHP client (that uses guzzle as composer dependency).
However, the patch doesn't seem to be applied as the same error occurs after installing the package with composer patch.
Relevant parts of the `composer.json` of that library:
```json
{
    // ...
    "require": {
        "php": ">=7.1",
        "ext-curl": "*",
        "ext-json": "*",
        "ext-mbstring": "*",
        "guzzlehttp/guzzle": "^6.2",
        "cweagans/composer-patches": "^1.6"
    },
    "require-dev": {
        "phpunit/phpunit": "^7.4",
        "squizlabs/php_codesniffer": "~2.6",
        "friendsofphp/php-cs-fixer": "~2.12"
    },
    "autoload": {
        "psr-4": { "OpenAPI\\Client\\" : "lib/" }
    },
    "autoload-dev": {
        "psr-4": { "OpenAPI\\Client\\" : "test/" }
    },
    "extra": {
        "patches": {
            "guzzlehttp/guzzle": {
                "Status code must be an integer value between 1xx and 5xx": "https://patch-diff.githubusercontent.com/raw/guzzle/guzzle/pull/2591.patch"
            }
        }
    }
}

````

**Comment by williamjulianvicary** [comment] 2020-10-01 11:57
For anyone tracking this, my PR was merged and is going to be released with 7.2 Guzzle release! :-)

**Comment by freekmurze** [comment] 2020-10-01 12:02
Fantastic, thanks for letting us know @williamjulianvicary

**Comment by Skullbock** [comment] 2020-10-01 12:47
@williamjulianvicary very nice work indeed! thanks!

**Comment by ClaudiuTodosia** [comment] 2020-10-01 13:48
@williamjulianvicary thank you!
